### ISSUE TITLE
Red Screen of Death after clicking on owned brewery

### ISSUE THREAD

**Issue by carlipford** [seanmbills/FamilyFriendlyBreweryTracker#134]
On the more screen, if the user clicks on a brewery that they have made, an error occurs.

TyperError: undefined is not an object (map.petFriendly)

This occurred with Carl's account (carlipford@gmail.com      Jdesign1!)

**Comment by seanmbills** [comment]
Not reproducible. Had Carl pull down Master and attempt to reproduce and wasn't possible. Likely addressed in one of Pete's branches after Carl had pulled down old master to test.
